version: '3.1'
services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./api/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./api/:/var/www/html/
    ports:
      - "8001:80"
