version: '3.1'
services:
  database:
    image: mariadb
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: shopping_cart
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: shopping_cart
      MYSQL_PASSWORD: "password"
